//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicle
    {
        public int Id { get; set; }
        public string vName { get; set; }
        public int customerId { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public System.DateTime modifiedDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
